### PR TITLE
Update ilc.py

### PR DESCRIPTION
**Pull request by JerreYjz**
Added ilc helper function, cleaned up the code.

### CODE REVIEW

**Comment by msyriac** [comment]
Why delete foregrounds.py? I actively use and love this module, warts and all :)

**Comment by nbatta** [comment]
> Why delete foregrounds.py? I actively use and love this module, warts and all :)

It's not deleted, just removed then added again.

**Comment by msyriac** [comment]
Ah ok, missed that, thanks.

**Comment by nbatta** [comment]
We're going to try this again.

**Pull request closed without merging**
